### ISSUE TITLE
image upload confusion

### ISSUE THREAD

**Issue by balmas** [PerseusDL/imgcollect_angular#14]
The image upload interface is a little confusing in terms of what it is doing with the image and data.  

It seems that as soon as you click Add, the image is uploaded and added to the file system.  However, no data object identifiers are assigned for these uploads until you add some metadata and click save (or click save on metadata without entering any data).  

So, I kept thinking that nothing was happening with my uploads because they weren't appearing in the list of uploads even though the add succeeded.

I think we also risk getting a lot of junk image files that are never used uploaded this way.  If creation of metadata is required for assignment of an identifier to an upload then we probably should postpone the upload of the image until the metadata is saved and the identifier assigned.

**Comment by caesarfeta** [comment]
https://github.com/PerseusDL/imgcollect_angular/pull/36
