### ISSUE TITLE
home page message doesn't change after user credentials acquired

### ISSUE THREAD

**Issue by balmas** [PerseusDL/imgcollect_angular#15]
to reproduce:

- access the home page without logging in to Perseids
- open Perseids in a new tab and login
- return to the original tab and click refresh.  User name now appears in the navbar but the home page message still says "To use imgcollect please login to Perseids and then refresh this page"

**Comment by caesarfeta** [comment]
https://github.com/PerseusDL/imgcollect_angular/pull/38
