### ISSUE TITLE
should an upload be able to be added multiple times to the same collection?

### ISSUE THREAD

**Issue by balmas** [PerseusDL/imgcollect_angular#17]
I'm not sure if it makes sense to allow a single collection to have multiple items for the same upload.  @caesarfeta was this intentional? I seem to recall a discussion about this where you raised a valid need for it, but I might be thinking about something else.

**Comment by caesarfeta** [comment]
@balmas I can see someone wanting the same upload to have multiple items in a collection. In my mind the item model can be a way of differentiating groups of ROIs. I was thinking of annotations at the time.  The same image can be annotated for different reasons, straight transcription, isolating interesting marginalia or illustrations etc.    If someone wants to create a collection to annotate the same image different ways by creating separate items for each task then we should let them.  I don't want to limit people unnecessarily.
