### ISSUE TITLE
need ability to remove an item from a collection

### ISSUE THREAD

**Issue by balmas** [PerseusDL/imgcollect_angular#25]
Interface should expose the ability to remove an item from a collection

**Comment by balmas** [comment]
should be limited for now to the user who was responsible for adding the item to the collection

**Comment by balmas** [comment]
one difficulty here is that we don't have any way right now to distinguish when an item in a collection has been "published" .. in theory we should not ever delete published CITE urns but instead redirect them elsewhere if the item is no longer available.  But when we are first setting up a collection or adding new it's important to be able to undo mistakes.  One way to address this would be to add a "status" field on an item, which we can set to a controlled list of terms  ("proposed","published","redirected") and to only allow deletion of e.g. "proposed" items

**Comment by caesarfeta** [comment]
https://github.com/PerseusDL/imgcollect_angular/pull/41
