### ISSUE TITLE
ability to automatically populate the label and description fields of an item from its upload

### ISSUE THREAD

**Issue by balmas** [PerseusDL/imgcollect_angular#28]
as right now the label and description are fairly redundant across the upload and item collections, we should probably offer the ability to automatically populate these fields from the upload when creating an item from an upload.

ideally this would be something that is configurable (i.e. the ability to configure a mapping between fields in a upload and item) and that the user can choose whether to do or not via the interface.

**Comment by caesarfeta** [comment]
https://github.com/PerseusDL/imgcollect_angular/pull/40
